### ISSUE TITLE
What's missing?

### ISSUE THREAD

**Issue by SirBisgaard** [CaiB/Emby-x-MAL#1]
Hi, I'm using Emby myself and MAL.

I wanted to know what is missing for being able to complete your add-on?
So I can use it myself.

**Comment by CaiB** [comment]
Hi there,

I pretty quickly abandoned this once I realized that there was already a plugin that could do this. In the Emby plugin catalogue, it's simply titled "Anime". You can configure where metadata gets pulled from on a per-library basis, so I disabled most of the sources except MAL, and this works pretty well.

**Comment by SirBisgaard** [comment]
Thanks for the information mate.

I will try it out and close the issue. 
Best of luck.

**Comment by SirBisgaard** [comment]
It works fine.
The only problem is i have grouped my anime movies together and cannot use MAL for "movies"... xD
So ill contact the developer directly instead. :) 

Well the repo will bring memories in a few years.. :+1:
